### ISSUE TITLE
停止调度时，报NPE

### ISSUE THREAD

**Issue by nmyphp** [nmyphp/tbschedule#5]
* 调度策略 > 停止
```
2019-05-23 21:32:47 INFO c.t.p.s.t.TBScheduleManager - 停止服务器 ：demoTask1$10.254.90.186$9ED0AB96BD5F4015AF1ECAE3B9B45785$0000000000
2019-05-23 21:32:47 ERROR c.t.p.s.s.TBScheduleManagerFactory - 注销任务错误：strategyName=DemoTask-strategy
java.lang.NullPointerException: null
	at com.taobao.pamirs.schedule.strategy.TBScheduleManagerFactory.stopServer(TBScheduleManagerFactory.java:282)
	at com.taobao.pamirs.schedule.strategy.TBScheduleManagerFactory.reRegisterManagerFactory(TBScheduleManagerFactory.java:188)
	at com.taobao.pamirs.schedule.strategy.TBScheduleManagerFactory.refresh(TBScheduleManagerFactory.java:177)
	at com.taobao.pamirs.schedule.strategy.ManagerFactoryTimerTask.run(TBScheduleManagerFactory.java:449)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

**Comment by nmyphp** [comment]
该异常不是每次都会出现，不影响调度

**Comment by likaiyong** [comment]
同时无法进入其他页面，可能由于采用不同的用户名密码配置过同一目录造zookeeper数据异常，可以在zookeeper中手动删除目录数据，或者更换新目录后重启应用。

在zookeeper中删除目录方法：

[root@192.168.1.5]$ ./zkClient.sh

[zk: localhost:2181(CONNECTED) 0] addauth digest admin:password

[zk: localhost:2181(CONNECTED) 1] rmr /app-schedule/demo

**Comment by nmyphp** [comment]
> 该异常不是每次都会出现，不影响调度

哪位愿意提PR修复
